#!/bin/sh

case "$1" in
    start)
        echo "Starting sct-app..."
        SDL_VIDEODRIVER=kmsdrm sct-app &
        ;;
    stop)
        echo "Stopping sct-app..."
        killall sct-app
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
